# Generated by Django 5.1.2 on 2024-11-14 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dalos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioNuevo',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='loginusuario',
            name='contraseña',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraseña_login', to='Dalos_app.usuarionuevo'),
        ),
        migrations.AddField(
            model_name='loginusuario',
            name='nombre_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_usuario_login', to='Dalos_app.usuarionuevo'),
        ),
    ]
